apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: certaur-system/certaur-serving-cert
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: centaur
  name: certaur-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: certaur-webhook-service
      namespace: certaur-system
      path: /mutate-certs-k8c-io-v1-certificate
  failurePolicy: Fail
  name: mcertificate.kb.io
  rules:
  - apiGroups:
    - certs.k8c.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - certificates
  sideEffects: None