apiVersion: v1
kind: Service
metadata:
  labels:
    app: certaur
  name: certaur-controller-manager-metrics-service
  namespace: certaur-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: centaur
  name: certaur-webhook-service
  namespace: certaur-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager