apiVersion: certs.k8c.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: centaur
    app.kubernetes.io/managed-by: kustomize
  name: certificate-sample
spec:
  dns: example.k8c.io
  validity: 60d
  secretRef:
    name: cert
