name: Operator CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.2
          golangci-lint version

      - name: Run golangci-lint
        run: |
          golangci-lint run --timeout=5m ./...

  security-check:
    name: Security Check (gosec)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.22
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec security check
        run: gosec ./...

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build operator image
        run: make docker-build

      - name: Push Docker image
        run: make docker-push

  build-installer:
    name: Build Installer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Installer YAML
        run: make build-installer

      - name: Upload installer YAML as artifact
        uses: actions/upload-artifact@v3
        with:
          name: operator-installer
          path: ./dist/certaur-*.yaml